# Generated by Django 3.2.4 on 2021-06-11 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(verbose_name='Data Início')),
                ('end', models.DateField(verbose_name='Data Fim')),
            ],
        ),
    ]
