# Generated by Django 3.2.4 on 2021-06-14 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tpm_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dates',
            new_name='Period',
        ),
    ]
