# Generated by Django 3.2.4 on 2021-06-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpm_api', '0003_auto_20210614_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='personName',
            field=models.CharField(max_length=255, null=True, verbose_name='Outra pessoa'),
        ),
    ]
