# Generated by Django 3.2.4 on 2021-06-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpm_api', '0005_alter_registration_personname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='personName',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Outra pessoa'),
        ),
    ]
